"""WS7 Agent Server/API 검증 (요구사항 §19, F13).

DoD: /agents/{id}/invoke 및 /stream API로 2개 이상 Agent를 동일 Runtime에서 서비스.
+ Health, Metadata, OpenAPI 자동생성, 404, Auth Adapter, execution_id 반환.
"""

import json

import pytest
from fastapi.testclient import TestClient

from klafi import RAGAgent, SimpleAgent
from klafi.server import AgentServer, create_app


@pytest.fixture
def client():
    server = AgentServer()
    # 2개 Agent를 동일 Runtime에 등록 (DoD)
    server.register(SimpleAgent(model=lambda p: f"simple:{p}"))
    server.register(RAGAgent(model=lambda p: "rag-answer", retriever=lambda q: ["d1"]))
    return TestClient(create_app(server))


def test_health(client):
    r = client.get("/health")
    assert r.status_code == 200 and r.json()["status"] == "ok"


def test_two_agents_served_same_runtime(client):
    r1 = client.post("/agents/simple/invoke", json={"input": {"question": "hi"}})
    r2 = client.post("/agents/rag/invoke", json={"input": {"question": "q"}})
    assert r1.status_code == 200 and r2.status_code == 200
    assert r1.json()["result"]["answer"] == "simple:hi"
    assert r2.json()["result"]["answer"] == "rag-answer"
    # 각 실행에 고유 execution_id + 상태
    assert len(r1.json()["execution_id"]) == 32
    assert r1.json()["state"] == "COMPLETED"
    assert r1.json()["execution_id"] != r2.json()["execution_id"]


def test_stream_ndjson(client):
    r = client.post("/agents/simple/stream", json={"input": {"question": "go"}})
    assert r.status_code == 200
    lines = [json.loads(l) for l in r.text.strip().splitlines()]
    assert lines and "chunk" in lines[-1]
    # 마지막 청크에 llm 노드 결과
    assert lines[-1]["chunk"]["llm"]["answer"] == "simple:go"


def test_metadata_and_list(client):
    assert {m["id"] for m in client.get("/agents").json()} == {"simple", "rag"}
    meta = client.get("/agents/rag").json()
    assert meta["agent_type"] == "rag" and meta["name"] == "RAG Agent"


def test_unknown_agent_404(client):
    r = client.post("/agents/nope/invoke", json={"input": {"question": "x"}})
    assert r.status_code == 404 and r.json()["error_code"] == "AGENT_NOT_FOUND"


def test_openapi_autogenerated(client):
    spec = client.get("/openapi.json").json()
    assert "/agents/{agent_id}/invoke" in spec["paths"]
    assert "/agents/{agent_id}/stream" in spec["paths"]


def test_business_error_returns_execution_id():
    server = AgentServer()

    def boom(p):
        raise ValueError("business failure")

    server.register(SimpleAgent(model=boom, spec=None), agent_id="bad")
    c = TestClient(create_app(server), raise_server_exceptions=False)
    r = c.post("/agents/bad/invoke", json={"input": {"question": "x"}})
    assert r.status_code == 500
    body = r.json()
    assert len(body["execution_id"]) == 32  # Trace 상관관계용 id 반환
    assert "business failure" in body["error"]


def test_auth_adapter_runs():
    server = AgentServer()
    seen = {}

    class CtxAgent(SimpleAgent):
        def build(self):
            from klafi.core.context import get_context
            from langgraph.graph import END, START, StateGraph
            from klafi.templates.simple import SimpleState

            g = StateGraph(SimpleState)

            def llm(s):
                seen["user"] = get_context().user_id  # Auth가 넣은 user가 Context에 보인다
                return {"answer": "ok"}

            g.add_node("llm", llm)
            g.add_edge(START, "llm")
            g.add_edge("llm", END)
            return g

    server.register(CtxAgent(model=lambda p: p), agent_id="a")
    c = TestClient(create_app(server, auth=lambda req: {"user_id": req.headers.get("x-user", "anon")}))
    r = c.post("/agents/a/invoke", json={"input": {"question": "x"}}, headers={"x-user": "alice"})
    assert r.status_code == 200
    assert seen["user"] == "alice"  # Authentication Adapter → security_context → ExecutionContext
